version: '3'
services:
  postgres:
    logging:
      driver: none
    # Heroku uses PostGIS 2.5.5 and PostgreSQL 13.5
    # This is technically not a valid combination
    # according to PostGIS and is therefore not
    # not an image they offer. We use PostgreSQL 12.x
    # and PostGIS 2.5.x instead.
    image: postgis/postgis:12-2.5
    environment:
      POSTGRES_DB: django
      POSTGRES_PASSWORD: postgres
    ports:
      - ${DOCKER_POSTGRES_PORT-5432}:5432

  rabbitmq:
    logging:
        driver: none
    image: rabbitmq:management
    ports:
      - ${DOCKER_RABBITMQ_PORT-5672}:5672
