version: '3'
services:
  postgres:
    logging:
      driver: none
    image: postgis/postgis:14-3.2
    environment:
      POSTGRES_DB: django
      POSTGRES_PASSWORD: postgres
    ports:
      - ${DOCKER_POSTGRES_PORT-5432}:5432

  rabbitmq:
    logging:
        driver: none
    image: rabbitmq:management
    ports:
      - ${DOCKER_RABBITMQ_PORT-5672}:5672
