# Generated by Django 3.2.8 on 2021-10-08 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_girder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionsMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='ContextMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_uri', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('color', models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green'), ('orange', 'orange'), ('purple', 'purple'), ('black', 'black')], default='red', max_length=15)),
                ('note', models.TextField(blank=True, max_length=1000)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('collaborators', models.ManyToManyField(related_name='collaborators', to=settings.AUTH_USER_MODEL)),
                ('connections_map', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.connectionsmap')),
                ('context_map', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.contextmap')),
                ('observers', models.ManyToManyField(related_name='observers', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contextmap',
            name='datasets',
            field=models.ManyToManyField(related_name='context_datasets', to='core.Dataset'),
        ),
        migrations.AddField(
            model_name='connectionsmap',
            name='pins',
            field=models.ManyToManyField(related_name='connection_pins', to='core.Pin'),
        ),
    ]
