# Generated by Django 3.2.9 on 2021-11-18 20:47

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_girder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('public', models.BooleanField(default=True)),
                ('source_uri', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    'color',
                    models.CharField(
                        choices=[
                            ('red', 'red'),
                            ('blue', 'blue'),
                            ('green', 'green'),
                            ('orange', 'orange'),
                            ('purple', 'purple'),
                            ('black', 'black'),
                        ],
                        default='red',
                        max_length=15,
                    ),
                ),
                ('note', models.TextField(blank=True, max_length=1000)),
                (
                    'dataset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='core.dataset'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('notes', models.TextField(blank=True, max_length=5000)),
                (
                    'datasets',
                    models.ManyToManyField(related_name='context_datasets', to='core.Dataset'),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                ('pins', models.ManyToManyField(related_name='connection_pins', to='core.Pin')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
