# Generated by Django 3.2.13 on 2022-04-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_base_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='failure',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
