# Generated by Django 3.2.11 on 2022-02-11 20:59

import atlascope.core.models.job_run
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_base_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrun',
            old_name='other_inputs',
            new_name='additional_inputs',
        ),
        migrations.RemoveField(
            model_name='jobrun',
            name='input_image',
        ),
        migrations.RemoveField(
            model_name='jobrun',
            name='preview_visual',
        ),
        migrations.RemoveField(
            model_name='jobrun',
            name='script',
        ),
        migrations.AddField(
            model_name='jobrun',
            name='job_type',
            field=models.CharField(default='average_color', max_length=100, validators=[atlascope.core.models.job_run.validate_job_type]),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='original_dataset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.dataset'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='JobScript',
        ),
    ]
