# Generated by Django 3.2.8 on 2021-10-26 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_main_five_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='connections_map',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.connectionsmap'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='context_map',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.contextmap'),
        ),
    ]
