# Generated by Django 3.2.13 on 2022-04-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_base_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='maximum_zoom',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='pin',
            name='minimum_zoom',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
