# Generated by Django 3.2.13 on 2022-05-16 21:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_base_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(default='My Tour', max_length=255)),
                (
                    'investigation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tours',
                        to='core.investigation',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('zoom', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourWaypoints',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('sequence', models.IntegerField(null=True)),
                (
                    'tour',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tour'
                    ),
                ),
                (
                    'waypoint',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to='core.waypoint'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='waypoints',
            field=models.ManyToManyField(through='core.TourWaypoints', to='core.Waypoint'),
        ),
    ]
