# Generated by Django 3.2.13 on 2022-05-04 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220426_1701'),
        ('core', '0003_job_failure'),
    ]

    operations = []
