# Generated by Django 3.2.9 on 2021-11-15 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_investigation_one_to_ones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigation',
            name='collaborators',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='observers',
        ),
    ]
