# Generated by Django 3.2.11 on 2022-01-06 21:17

from django.db import migrations, models
import django.db.models.deletion
import s3_file_field.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_new_dataset_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('input_image', s3_file_field.fields.S3FileField(null=True)),
                ('other_inputs', models.JSONField(null=True)),
                ('outputs', models.JSONField(null=True)),
                ('last_run', models.DateTimeField(null=True)),
                ('preview_visual', s3_file_field.fields.S3FileField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobScript',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('script_contents', s3_file_field.fields.S3FileField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobRunOutputImage',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('stored_image', s3_file_field.fields.S3FileField(null=True)),
                (
                    'job_run',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="output_images",
                        to='core.jobrun',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='jobrun',
            name='script',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='core.jobscript'
            ),
        ),
    ]
