# Generated by Django 3.2.10 on 2022-01-04 19:20

import uuid

from django.db import migrations, models
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_new_dataset_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('script_contents', s3_file_field.fields.S3FileField(null=True)),
                ('input_image', s3_file_field.fields.S3FileField(null=True)),
                ('other_inputs', models.JSONField(null=True)),
                ('outputs', models.JSONField(null=True)),
                ('last_run', models.DateTimeField(null=True)),
                ('preview_visual', s3_file_field.fields.S3FileField(null=True)),
            ],
        ),
    ]
