# Generated by Django 3.2.13 on 2022-05-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_dataset_dataset_type'),
        ('core', '0005_add_tour_waypoints'),
    ]

    operations = []
