# Generated by Django 3.2.13 on 2022-05-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_tour_waypoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='scale',
            field=models.TextField(blank=True, choices=[('tissue', 'tissue'), ('gland', 'gland'), ('cell', 'cell')], null=True),
        ),
    ]
