# Generated by Django 3.2.11 on 2022-02-23 16:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_embeddings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='dataset',
        ),
        migrations.AddField(
            model_name='pin',
            name='child_dataset',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='locations',
                to='core.dataset',
            ),
        ),
        migrations.AddField(
            model_name='pin',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pin',
            name='parent_dataset',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='pins',
                to='core.dataset',
            ),
            preserve_default=False,
        ),
    ]
