# Generated by Django 3.2.11 on 2022-01-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='source_uri',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddConstraint(
            model_name='dataset',
            constraint=models.CheckConstraint(check=models.Q(('content__isnull', False), models.Q(('source_uri__isnull', False), ('importer__isnull', False), _connector='OR')), name='has_no_source'),
        ),
    ]
