# Generated by Django 3.2.13 on 2022-05-27 19:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_tour_waypoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='dataset_type',
            field=models.CharField(
                choices=[
                    ('tile_source', 'tile_source'),
                    ('tile_overlay', 'tile_overlay'),
                    ('analytics', 'analytics'),
                    ('subimage', 'subimage'),
                    ('nucleus_detection', 'nucleus_detection'),
                ],
                default='tile_source',
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='DetectedNucleus',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('label_integer', models.IntegerField()),
                ('centroid', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('weighted_centroid', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('bounding_box', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('orientation', models.FloatField()),
                ('nucleus_gradient', models.JSONField()),
                ('nucleus_haralick', models.JSONField()),
                ('nucleus_intensity', models.JSONField()),
                ('shape', models.JSONField()),
                ('size', models.JSONField()),
                (
                    'detection_dataset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='detected_nuclei',
                        to='core.dataset',
                    ),
                ),
            ],
        ),
    ]
