# Generated by Django 3.2.13 on 2022-06-01 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20220527_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='note',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='pin',
            old_name='child_location',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='child',
        ),
        migrations.CreateModel(
            name='NotePin',
            fields=[
                ('pin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pin')),
                ('note', models.TextField(max_length=1000)),
            ],
            bases=('core.pin',),
        ),
        migrations.CreateModel(
            name='DatasetPin',
            fields=[
                ('pin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pin')),
                ('child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.dataset')),
            ],
            bases=('core.pin',),
        ),
    ]
