# Generated by Django 3.2.11 on 2022-03-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_context_investigations'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
