# Generated by Django 3.2.13 on 2022-06-28 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dataset_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='child_location',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='child',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='note',
        ),
        migrations.CreateModel(
            name='NotePin',
            fields=[
                (
                    'pin_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='core.pin',
                    ),
                ),
                ('note', models.TextField(max_length=1000)),
            ],
            bases=('core.pin',),
        ),
        migrations.CreateModel(
            name='DatasetPin',
            fields=[
                (
                    'pin_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='core.pin',
                    ),
                ),
                ('description', models.TextField(blank=True, max_length=1000)),
                (
                    'child',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='locations',
                        to='core.dataset',
                    ),
                ),
            ],
            bases=('core.pin',),
        ),
    ]
