# Generated by Django 3.2.12 on 2022-03-02 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_job_completion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='public',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='owner',
        ),
    ]
