# Generated by Django 3.2.13 on 2022-07-07 17:02

import django.contrib.postgres.indexes
from django.db import migrations

import atlascope.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pin_types'),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS cube;"),
        migrations.AddField(
            model_name='detectednucleus',
            name='fingerprint',
            field=atlascope.core.fields.CubeField(default=atlascope.core.fields.Cube([])),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='detectednucleus',
            index=django.contrib.postgres.indexes.GistIndex(
                fields=['fingerprint'], name='core_detect_fingerp_c99ddd_gist'
            ),
        ),
    ]
