# Generated by Django 3.2.13 on 2022-07-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_detected_structures'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedstructure',
            name='structure_type',
            field=models.CharField(default='nucleus', max_length=10),
        ),
    ]
