# Generated by Django 3.2.14 on 2022-08-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_3dvolume_dataset_type'),
        ('core', '0009_detectednucleus_fingerprint'),
    ]

    operations = []
