# Generated by Django 3.2.12 on 2022-04-09 17:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_dataset_dataset_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('zoom', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourWaypoints',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('sequence', models.IntegerField(null=True)),
                (
                    'tour',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tour'
                    ),
                ),
                (
                    'way_point',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to='core.waypoint'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='way_points',
            field=models.ManyToManyField(through='core.TourWaypoints', to='core.Waypoint'),
        ),
    ]
