# Generated by Django 3.2.12 on 2022-03-24 17:09

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_dataset_dataset_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('way_points', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326), null=True, size=None), null=True, size=None)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='core.investigation')),
            ],
        ),
    ]
