# Generated by Django 3.2.13 on 2022-08-16 15:51

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion

import atlascope.core.fields.cube


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20220816_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedStructure',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('label_integer', models.IntegerField()),
                ('centroid', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('weighted_centroid', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('bounding_box', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('structure_type', models.CharField(default='nucleus', max_length=10)),
                ('fingerprint', atlascope.core.fields.cube.CubeField()),
                ('gradient_canny_mean', models.FloatField()),
                ('gradient_canny_sum', models.FloatField()),
                ('gradient_mag_histenergy', models.FloatField()),
                ('gradient_mag_histentropy', models.FloatField()),
                ('gradient_mag_kurtosis', models.FloatField()),
                ('gradient_mag_mean', models.FloatField()),
                ('gradient_mag_skewness', models.FloatField()),
                ('gradient_mag_std', models.FloatField()),
                ('haralick_asm_mean', models.FloatField()),
                ('haralick_asm_range', models.FloatField()),
                ('haralick_contrast_mean', models.FloatField()),
                ('haralick_contrast_range', models.FloatField()),
                ('haralick_correlation_mean', models.FloatField()),
                ('haralick_correlation_range', models.FloatField()),
                ('haralick_differenceentropy_mean', models.FloatField()),
                ('haralick_differenceentropy_range', models.FloatField()),
                ('haralick_differencevariance_mean', models.FloatField()),
                ('haralick_differencevariance_range', models.FloatField()),
                ('haralick_entropy_mean', models.FloatField()),
                ('haralick_entropy_range', models.FloatField()),
                ('haralick_idm_mean', models.FloatField()),
                ('haralick_idm_range', models.FloatField()),
                ('haralick_imc1_mean', models.FloatField()),
                ('haralick_imc1_range', models.FloatField()),
                ('haralick_imc2_mean', models.FloatField()),
                ('haralick_imc2_range', models.FloatField()),
                ('haralick_sumaverage_mean', models.FloatField()),
                ('haralick_sumaverage_range', models.FloatField()),
                ('haralick_sumentropy_mean', models.FloatField()),
                ('haralick_sumentropy_range', models.FloatField()),
                ('haralick_sumofsquares_mean', models.FloatField()),
                ('haralick_sumofsquares_range', models.FloatField()),
                ('haralick_sumvariance_mean', models.FloatField()),
                ('haralick_sumvariance_range', models.FloatField()),
                ('intensity_histenergy', models.FloatField()),
                ('intensity_histentropy', models.FloatField()),
                ('intensity_iqr', models.FloatField()),
                ('intensity_kurtosis', models.FloatField()),
                ('intensity_mad', models.FloatField()),
                ('intensity_max', models.FloatField()),
                ('intensity_mean', models.FloatField()),
                ('intensity_meanmediandiff', models.FloatField()),
                ('intensity_median', models.FloatField()),
                ('intensity_min', models.FloatField()),
                ('intensity_skewness', models.FloatField()),
                ('intensity_std', models.FloatField()),
                ('orientation', models.FloatField()),
                ('shape_circularity', models.FloatField()),
                ('shape_eccentricity', models.FloatField()),
                ('shape_equivalentdiameter', models.FloatField()),
                ('shape_extent', models.FloatField()),
                ('shape_fsd1', models.FloatField()),
                ('shape_fsd2', models.FloatField()),
                ('shape_fsd3', models.FloatField()),
                ('shape_fsd4', models.FloatField()),
                ('shape_fsd5', models.FloatField()),
                ('shape_fsd6', models.FloatField()),
                ('shape_fractaldimension', models.FloatField()),
                ('shape_humoments1', models.FloatField()),
                ('shape_humoments2', models.FloatField()),
                ('shape_humoments3', models.FloatField()),
                ('shape_humoments4', models.FloatField()),
                ('shape_humoments5', models.FloatField()),
                ('shape_humoments6', models.FloatField()),
                ('shape_humoments7', models.FloatField()),
                ('shape_minormajoraxisratio', models.FloatField()),
                ('shape_solidity', models.FloatField()),
                ('shape_weightedhumoments1', models.FloatField()),
                ('shape_weightedhumoments2', models.FloatField()),
                ('shape_weightedhumoments3', models.FloatField()),
                ('shape_weightedhumoments4', models.FloatField()),
                ('shape_weightedhumoments5', models.FloatField()),
                ('shape_weightedhumoments6', models.FloatField()),
                ('shape_weightedhumoments7', models.FloatField()),
                ('size_area', models.FloatField()),
                ('size_convexhullarea', models.FloatField()),
                ('size_majoraxislength', models.FloatField()),
                ('size_minoraxislength', models.FloatField()),
                ('size_perimeter', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_type',
            field=models.CharField(
                choices=[
                    ('tile_source', 'tile_source'),
                    ('tile_overlay', 'tile_overlay'),
                    ('analytics', 'analytics'),
                    ('subimage', 'subimage'),
                    ('structure_detection', 'structure_detection'),
                    ('non_tiled_image', 'non_tiled_image'),
                    ('3d_volume', '3d_volume'),
                ],
                default='tile_source',
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name='DetectedNucleus',
        ),
        migrations.AddField(
            model_name='detectedstructure',
            name='detection_dataset',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='detected_structures',
                to='core.dataset',
            ),
        ),
        migrations.AddIndex(
            model_name='detectedstructure',
            index=django.contrib.postgres.indexes.GistIndex(
                fields=['fingerprint'], name='core_detect_fingerp_b3c13d_gist'
            ),
        ),
    ]
