<template>
  <v-list-item-content
    :set="dataset = linkedDataset(pin)"
  >
    <v-list-item-title>{{ pinDisplayTitle(pin) }}</v-list-item-title>
    <v-list-item-subtitle
      v-for="info in additionalInfo(dataset)"
      :key="info"
    >
      {{ info }}
    </v-list-item-subtitle>
    <div
      v-for="visOption in visOptions(dataset)"
      v-show="active"
      :key="visOption.value"
      :set="showOptions = visualizationsShown.map(vis => vis.value).includes(visOption.value)"
      @click="(event) => event.stopPropagation()"
    >
      <v-checkbox
        :value="showOptions"
        :label="visOption.text"
        hide-details
        @change="() => updateVisualizationsShown(visOption)"
      />
      <div
        v-if="showOptions"
        class="px-5"
      >
        <v-checkbox
          v-for="available in visOption.availableOptions"
          :key="available.value"
          :label="available.text"
          dense
          hide-details
          class="my-0 py-0"
          @change="() => updateOption(visOption, available.value)"
        />
      </div>
    </div>
  </v-list-item-content>
</template>

<script lang="ts">
import { Dataset, Pin, VisOption } from '@/generatedTypes/AtlascopeTypes';
import visualize, { visualizeDetectedStructures } from '@/utilities/analyticsVis';
import {
  computed, defineComponent, watch,
} from '@vue/composition-api';
import store from '../store';

export default defineComponent({
  props: {
    pin: {
      type: Object,
      required: true,
    },
    active: {
      type: Boolean,
      required: true,
    },
  },
  setup() {
    const rootDataset = computed(() => store.state.rootDataset);
    const currentDatasets = computed(() => store.state.currentDatasets);
    const visualizationLayer = computed(() => store.state.visualizationLayer);
    const visualizationsShown = computed(() => store.state.visualizationsShown);
    const { updateVisualizationsShown, updateVisualizationOption } = store.commit;

    function pinDisplayTitle(pin: Pin) {
      return pin.description?.replace('Generated by', 'Results of') || 'Job results';
    }
    function linkedDataset(pin: Pin) {
      return currentDatasets.value.find(
        (dataset: Dataset) => dataset.id === pin.child,
      );
    }
    function additionalInfo(dataset: Dataset) {
      const info = [
        dataset.name,
        dataset.metadata?.origin,
      ];
      if (dataset.dataset_type?.includes('_detection')) {
        info.push(`${dataset.detected_structures.length} structures detected`);
      }
      return info;
    }
    function visOptions(dataset: Dataset) {
      const availableVisualizations = [];
      if (dataset.dataset_type?.includes('_detection')) {
        availableVisualizations.push({
          value: `dataset_${dataset.id}_show_centroids`,
          text: 'Centroid locations',
          data: dataset,
          visFunc: visualizeDetectedStructures,
          options: [],
          availableOptions: [
            {
              value: 'show_distances_on_hover',
              text: 'Show distances on hover',
            },
          ],
        });
      }
      return availableVisualizations;
    }
    function updateVis() {
      if (visualizationLayer.value) {
        visualizationLayer.value.layer.value.clear();
        visualizationLayer.value.layer.value.draw();
        visualize(
          visualizationsShown.value,
          visualizationLayer.value,
        );
      }
    }
    function updateOption(visOption: VisOption, target: string) {
      const copy = visualizationsShown.value.find(
        (vis) => vis.value === visOption.value,
      );
      if (!copy) return;
      if (copy.options.includes(target)) {
        copy.options = copy.options.filter(
          (opt) => opt !== target,
        );
      } else {
        copy.options.push(target);
      }
      updateVisualizationOption(copy);
      updateVis();
    }
    watch(visualizationsShown, updateVis, { deep: true });

    return {
      rootDataset,
      pinDisplayTitle,
      linkedDataset,
      additionalInfo,
      visOptions,
      visualizationsShown,
      updateVisualizationsShown,
      updateOption,
      updateVis,
    };
  },
});
</script>
