name: ci
on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - "web/**"
  schedule:
    - cron: "0 0 * * *"
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        test-type: [lint, check-migrations, test]
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: django
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
      rabbitmq:
        image: rabbitmq:management
        ports:
          - 5672:5672
      minio:
        # This image does not require any command arguments (which GitHub Actions don't support)
        image: bitnami/minio:latest
        env:
          MINIO_ACCESS_KEY: minioAccessKey
          MINIO_SECRET_KEY: minioSecretKey
        ports:
          - 9000:9000
    steps:
      - name: Install dependencies
        run: |
          # Install system libraries for Python packages:
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install --no-install-recommends --yes \
            `# C compilers and C standard library development files` \
            gcc libc6-dev \
            `# Python` \
            python-is-python3 python3-dev python3-pip \
            `# PostgreSQL library development files (psycopg2)` \
            libpq-dev
        shell: bash
      - uses: actions/checkout@v2
      - name: Install tox
        run: |
          pip install --upgrade pip
          pip install tox
      - name: Run tests
        run: |
          tox -e ${{matrix.test-type}}
        env:
          DJANGO_DATABASE_URL: postgres://postgres:postgres@localhost:5432/django
          DJANGO_MINIO_STORAGE_ENDPOINT: localhost:9000
          DJANGO_MINIO_STORAGE_ACCESS_KEY: minioAccessKey
          DJANGO_MINIO_STORAGE_SECRET_KEY: minioSecretKey
